name: Github Page

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          version: '22.11'
          cache: yarn
      - name: Install packages
        run: yarn install
      - name: Set Environment Variables
        env:
          BASE_PATH: /
        run: |
          echo "" > .env
          echo NEXT_PUBLIC_APP_NAME=Ali Bey >> .env
          echo NEXT_PUBLIC_APP_DESCRIPTION=A Turkish Mediterranean restaurant in the heart of Sutton >> .env
          echo NEXT_PUBLIC_APP_URL=https://alibey.co.uk/ >> .env
      - name: Build
        run: yarn build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
